### ISSUE TITLE
NameError: name 'WORST_COUNT_CHANGE_GENERATIONS' is not defined

### ISSUE THREAD

**Issue by triffid** [demipixel/factorio-beacon-evolver#1]
```
Traceback (most recent call last):
  File "index.py", line 100, in <module>
    run(config_path)
  File "index.py", line 95, in run
    winner = p.run(eval_genomes, NUM_GENERATIONS)
  File "/home/triffid/.local/lib64/python3.4/site-packages/neat/population.py", line 89, in run
    fitness_function(list(iteritems(self.population)), self.config)
  File "index.py", line 63, in eval_genomes
    if gen % WORST_COUNT_CHANGE_GENERATIONS == 0:
NameError: name 'WORST_COUNT_CHANGE_GENERATIONS' is not defined
```

Should it be WORST_COUNT_STEP_GENERATIONS ?

**Comment by demipixel** [comment]
Thanks.
